version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rhombus
      MYSQL_USER: rhombus
      MYSQL_PASSWORD: rhombus
    ports:
      - "3306:3306"
