name: Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        shell: "bash"
        run: pnpm install

      - name: Generate Prisma schema
        shell: "bash"
        run: cd app && pnpm prisma generate

      - name: Lint
        shell: "bash"
        run: pnpm lint

      - name: Typecheck
        shell: "bash"
        run: pnpm typecheck
